local nnoremap = require("b.keymap").nnoremap

nnoremap("<C-p>", ":Telescope")
nnoremap("<Leader>fw", function()
  require("telescope.builtin").grep_string()
end)
nnoremap("<Leader>ft", function()
  require('telescope.builtin').live_grep()
end)
nnoremap("<Leader>ff", function()
  require('telescope.builtin').find_files()
end)
nnoremap("<Leader>fb", function()
  require('telescope.builtin').buffers()
end)
nnoremap("<Leader>fg", function()
  require('telescope.builtin').git_files()
end)
nnoremap("<Leader>fp", ":lua require'telescope'.extensions.project.project{}<CR>")
